### ISSUE TITLE
"Route objects exist, but prefix not seen in DFZ" not always correct.

### ISSUE THREAD

**Issue by jayb-github** [dashcare/irrexplorer#51] opened 2021-05-24 16:32 UTC
For example, https://irrexplorer.dashcare.nl/prefix/12.137.136.0/21
indicates that for 12.0.0.0/8 "Route objects exist, but prefix not seen in DFZ" but that is incorrect.  as7018 announces 12.0.0.0/8, 12.0.0.0/9, and 12.128.0.0/9 -- all should be seen in the DFZ.

**Comment by mxsasha** [comment] 2021-06-03 19:09
This is caused by a workaround for a limitation in a datafeed. Being worked on :)

**Comment by mxsasha** [comment] 2021-06-18 10:30
This was caused by my bad workaround for limitations of the BGP feed. Switched to a different feed and reversed my workaround and this is fixed now.

**Closed by mxsasha** 2021-06-18 10:30 UTC
